DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS vendors;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS shareholders;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS investments;
DROP TABLE IF EXISTS dividends;
